package:
  name: oillibrary
  version: 0.1

# no source -- source is local

requirements:
  build:
    - python
    - numpy
    - setuptools
    - sqlalchemy
    - transaction
    - zope.sqlalchemy
    - awesome-slugify
    - unit_conversion
    - pytest
    - repoze.lru
  run:
    - numpy
    - python
    - sqlalchemy
    - transaction
    - zope.sqlalchemy
    - awesome-slugify
    - pytest
    - unit_conversion
    - repoze.lru

about:
  home: https://github.com/NOAA-ORR-ERD/PyGnome
  license: Public Domain


